import { StyleSheet, Dimensions } from 'react-native';

const SCREEN_WIDTH = Dimensions.get('window').width;
const DPAD_SIZE = 180;
const ARM_THICKNESS = DPAD_SIZE * 0.4;
const ACCENT_COLOR_ORANGE = '#FF833A';
const OUTLINE_COLOR_BLUE = '#121212';

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#121212', alignItems: 'center' },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 15,
    paddingTop: 30,
  },
  backButton: { margin: 2 },
  backCircle: {
    width: 40,
    height: 40,
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'white',
    justifyContent: 'center',
    alignItems: 'center',
  },
  titleContainer: { flex: 1, alignItems: 'center', marginRight: 40 },
  subtitle: {
    color: 'white',
    fontSize: 22,
    fontWeight: '300',
    fontFamily: 'Shantell',
  },
  statusBar: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '100%',
    marginTop: 20,
    paddingHorizontal: 10,
  },
  statusItem: { alignItems: 'center' },
  statusLabel: { color: 'white', fontSize: 12, marginTop: 4 },
  statusValue: { color: 'white', fontSize: 14, fontWeight: 'bold' },
  statusValueGreen: { color: '#34C759', fontSize: 14, fontWeight: 'bold' },
  statusIconBG: {
    width: 22,
    height: 22,
    borderRadius: 11,
    backgroundColor: 'rgba(255, 154, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  statusIconInner: {
    width: 14,
    height: 14,
    borderRadius: 7,
    backgroundColor: '#FF833A',
  },
  coordsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '90%',
    marginTop: 15,
  },
  coordsText: { color: '#FF833A', fontSize: 14, fontFamily: 'Shantell' },
  waveformArea: {
    height: 220,
    marginTop: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  waveformContainer: {
    width: SCREEN_WIDTH,
    height: 150,
    flexDirection: 'row',
    alignItems: 'flex-end',
    justifyContent: 'space-evenly',
    paddingBottom: 10,
    position: 'relative',
  },
  waveBar: { backgroundColor: 'white', width: 2 },
  playhead: {
    position: 'absolute',
    left: '50%',
    height: '70%',
    width: 3,
    backgroundColor: '#FF833A',
    marginLeft: -1.5,
    borderRadius: 2,
    top: 30,
  },
  cursor: {
    position: 'absolute',
    height: 100,
    width: 3,
    backgroundColor: '#34C759',
    borderRadius: 2,
    zIndex: 10,
  },
  frequencyText: {
    color: '#FF833A',
    fontSize: 16,
    marginBottom: 10,
    fontFamily: 'Shantell',
  },
  swipeHint: { color: '#666', fontSize: 12, marginTop: 5, fontStyle: 'italic' },
  freqControls: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    width: '80%',
    marginVertical: 15,
  },
  freqButton: {
    backgroundColor: '#FF833A',
    width: 50,
    height: 40,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  freqButtonText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: 'white',
    lineHeight: 24,
  },
  bottomBar: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    alignItems: 'center',
    width: '100%',
    paddingHorizontal: 15,
    marginTop: 15,
  },
  bottomButtonCircle: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FF833A',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
    margin: 5,
  },
  bottomButtonCirclePurple: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#9b59b6',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
    margin: 5,
  },
  bottomButtonCircleRed: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#FF3B30',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
    margin: 5,
  },
  bottomButtonText: {
    color: 'white',
    fontFamily: 'Shantell',
    fontSize: 8,
    textAlign: 'center',
  },
  recPauseButton: {
    backgroundColor: '#FF833A',
    width: 80,
    height: 40,
    borderRadius: 20,
    justifyContent: 'center',
    alignItems: 'center',
    margin: 5,
  },
  modalContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
  },
  modalContent: {
    width: 320,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(0,0,0,0.8)',
    borderWidth: 2,
    borderColor: '#FF833A',
    borderStyle: 'dashed',
    borderRadius: 50,
  },
  modalTitle: {
    color: 'white',
    fontSize: 18,
    marginBottom: 15,
  },
  input: {
    width: '100%',
    height: 60,
    backgroundColor: '#2C2C2E',
    borderRadius: 25,
    color: 'white',
    paddingHorizontal: 10,
    marginBottom: 15,
  },
  modalButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
  },
  modalButton: {
    backgroundColor: '#FF833A',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 25,
  },
  modalButtonText: {
    color: 'white',
    fontSize: 16,
  },
  dpadContainer: {
    width: DPAD_SIZE,
    height: DPAD_SIZE,
    position: 'relative',
    justifyContent: 'center',
    alignItems: 'center',
    marginVertical: 20,
  },
  dpadArm: {
    position: 'absolute',
    borderRadius: 15,
  },
  dpadHorizontal: {
    width: '100%',
    height: ARM_THICKNESS,
    backgroundColor: ACCENT_COLOR_ORANGE,
  },
  dpadVertical: {
    width: ARM_THICKNESS,
    height: '100%',
    backgroundColor: ACCENT_COLOR_ORANGE,
  },
  dpadHorizontalOutline: {
    width: `103%`,
    height: ARM_THICKNESS + 6,
    backgroundColor: OUTLINE_COLOR_BLUE,
  },
  dpadVerticalOutline: {
    width: ARM_THICKNESS + 6,
    height: `103%`,
    backgroundColor: OUTLINE_COLOR_BLUE,
  },
  dpadButton: {
    position: 'absolute',
    justifyContent: 'center',
    alignItems: 'center',
    width: ARM_THICKNESS,
    height: ARM_THICKNESS,
  },
  dpadButtonUp: {
    top: 0,
    alignSelf: 'center',
  },
  dpadButtonDown: {
    bottom: 0,
    alignSelf: 'center',
  },
  dpadButtonLeft: {
    left: 0,
    top: 0,
    height: '100%',
  },
  dpadButtonRight: {
    right: 0,
    top: 0,
    height: '100%',
  },
  centerButton: {
    position: 'absolute',
    width: DPAD_SIZE * 0.4,
    height: DPAD_SIZE * 0.4,
    justifyContent: 'center',
    alignItems: 'center',
  },
  centerButtonGlow: {
    width: '100%',
    height: '100%',
    borderRadius: (DPAD_SIZE * 0.4) / 2,
    backgroundColor: 'black',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: ACCENT_COLOR_ORANGE,
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 1,
    shadowRadius: 10,
    elevation: 15,
  },
  centerButtonCore: {
    width: '70%',
    height: '70%',
    borderRadius: (DPAD_SIZE * 0.4 * 0.7) / 2,
    backgroundColor: 'black',
    borderWidth: 4,
    borderColor: ACCENT_COLOR_ORANGE,
  },
});

export default styles