/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/connected`; params?: Router.UnknownInputParams; } | { pathname: `/coordinate`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/loading`; params?: Router.UnknownInputParams; } | { pathname: `/menu/about-us`; params?: Router.UnknownInputParams; } | { pathname: `/menu/free-use-mode`; params?: Router.UnknownInputParams; } | { pathname: `/menu/learning-center`; params?: Router.UnknownInputParams; } | { pathname: `/menu/learning-center/mission`; params?: Router.UnknownInputParams; } | { pathname: `/menu/learning-center/modules`; params?: Router.UnknownInputParams; } | { pathname: `/menu/learning-center/modules/module-details`; params?: Router.UnknownInputParams; } | { pathname: `/menu/saved-signal-detail`; params?: Router.UnknownInputParams; } | { pathname: `/menu/saved-signal-list`; params?: Router.UnknownInputParams; } | { pathname: `/menu/settings`; params?: Router.UnknownInputParams; } | { pathname: `/menu/target-tracking-list`; params?: Router.UnknownInputParams; } | { pathname: `/menu/target-tracking-mode`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/connected`; params?: Router.UnknownOutputParams; } | { pathname: `/coordinate`; params?: Router.UnknownOutputParams; } | { pathname: `/dashboard`; params?: Router.UnknownOutputParams; } | { pathname: `/loading`; params?: Router.UnknownOutputParams; } | { pathname: `/menu/about-us`; params?: Router.UnknownOutputParams; } | { pathname: `/menu/free-use-mode`; params?: Router.UnknownOutputParams; } | { pathname: `/menu/learning-center`; params?: Router.UnknownOutputParams; } | { pathname: `/menu/learning-center/mission`; params?: Router.UnknownOutputParams; } | { pathname: `/menu/learning-center/modules`; params?: Router.UnknownOutputParams; } | { pathname: `/menu/learning-center/modules/module-details`; params?: Router.UnknownOutputParams; } | { pathname: `/menu/saved-signal-detail`; params?: Router.UnknownOutputParams; } | { pathname: `/menu/saved-signal-list`; params?: Router.UnknownOutputParams; } | { pathname: `/menu/settings`; params?: Router.UnknownOutputParams; } | { pathname: `/menu/target-tracking-list`; params?: Router.UnknownOutputParams; } | { pathname: `/menu/target-tracking-mode`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/connected${`?${string}` | `#${string}` | ''}` | `/coordinate${`?${string}` | `#${string}` | ''}` | `/dashboard${`?${string}` | `#${string}` | ''}` | `/loading${`?${string}` | `#${string}` | ''}` | `/menu/about-us${`?${string}` | `#${string}` | ''}` | `/menu/free-use-mode${`?${string}` | `#${string}` | ''}` | `/menu/learning-center${`?${string}` | `#${string}` | ''}` | `/menu/learning-center/mission${`?${string}` | `#${string}` | ''}` | `/menu/learning-center/modules${`?${string}` | `#${string}` | ''}` | `/menu/learning-center/modules/module-details${`?${string}` | `#${string}` | ''}` | `/menu/saved-signal-detail${`?${string}` | `#${string}` | ''}` | `/menu/saved-signal-list${`?${string}` | `#${string}` | ''}` | `/menu/settings${`?${string}` | `#${string}` | ''}` | `/menu/target-tracking-list${`?${string}` | `#${string}` | ''}` | `/menu/target-tracking-mode${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/connected`; params?: Router.UnknownInputParams; } | { pathname: `/coordinate`; params?: Router.UnknownInputParams; } | { pathname: `/dashboard`; params?: Router.UnknownInputParams; } | { pathname: `/loading`; params?: Router.UnknownInputParams; } | { pathname: `/menu/about-us`; params?: Router.UnknownInputParams; } | { pathname: `/menu/free-use-mode`; params?: Router.UnknownInputParams; } | { pathname: `/menu/learning-center`; params?: Router.UnknownInputParams; } | { pathname: `/menu/learning-center/mission`; params?: Router.UnknownInputParams; } | { pathname: `/menu/learning-center/modules`; params?: Router.UnknownInputParams; } | { pathname: `/menu/learning-center/modules/module-details`; params?: Router.UnknownInputParams; } | { pathname: `/menu/saved-signal-detail`; params?: Router.UnknownInputParams; } | { pathname: `/menu/saved-signal-list`; params?: Router.UnknownInputParams; } | { pathname: `/menu/settings`; params?: Router.UnknownInputParams; } | { pathname: `/menu/target-tracking-list`; params?: Router.UnknownInputParams; } | { pathname: `/menu/target-tracking-mode`; params?: Router.UnknownInputParams; } | `/+not-found${`?${string}` | `#${string}` | ''}` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
